deployment/conf_files/etc/openvnet/common.conf
deployment/conf_files/etc/openvnet/vna.conf
deployment/conf_files/etc/openvnet/vnmgr.conf
deployment/conf_files/etc/openvnet/webapi.conf
vnet/bin/vna
vnet/bin/vnmgr
vnet/lib/vnet/configurations/vna.rb
vnet/lib/vnet/configurations/vnmgr.rb
vnet/lib/vnet/configurations/webapi.rb
vnet/rack/config-webapi.ru

There is a need to specify global IP address for the agents in its configuration file and DCell.start.

Fix dcell start

---

deployment/conf_files/usr/bin/vnctl

When installing the `openvnet-vnctl`RPM, vnctl wouldn't start unless ruby was in the `PATH` variable.
Since vnctl depends on `openvnet-ruby`, it should use that one but we can't put it in the user's `PATH`. they might have another ruby in there. Also, I don't want to have a shebang that hard codes vnctl to use the binary that `openvnet-ruby` provides.
Have the shell script `/usr/bin/vnctl` (which is installed with the `openvnet-vnctl` RPM) check if the `openvnet-ruby` binary exists. Use it if it exists, otherwise run vnctl directly which will make it use whatever ruby is in `PATH`

Bugfix run vnctl without ruby in PATH

---

deployment/conf_files/etc/openvnet/vnctl.conf
vnctl/Gemfile
vnctl/Gemfile.lock
vnctl/lib/vnctl.rb
vnctl/lib/vnctl/cli/base.rb
vnctl/lib/vnctl/cli/datapath.rb
vnctl/lib/vnctl/cli/dns_service.rb
vnctl/lib/vnctl/cli/interface.rb
vnctl/lib/vnctl/cli/ip_lease.rb
vnctl/lib/vnctl/cli/ip_range_group.rb
vnctl/lib/vnctl/cli/lease_policies.rb
vnctl/lib/vnctl/cli/mac_lease.rb
vnctl/lib/vnctl/cli/network.rb
vnctl/lib/vnctl/cli/network_service.rb
vnctl/lib/vnctl/cli/route.rb
vnctl/lib/vnctl/cli/route_link.rb
vnctl/lib/vnctl/cli/security_group.rb
vnctl/lib/vnctl/cli/translation.rb
vnctl/lib/vnctl/cli/vlan_translation.rb
vnctl/lib/vnctl/configuration/vnctl.rb
vnctl/lib/vnctl/webapi.rb

I miss programming a bit so I decided to quickly remove the httparty library from vnctl. Ruby has a perfectly usable HTTP class in the standard library and less dependencies is better.

Vnctl remove httparty

---

deployment/packagebuild/packages.d/vnet/openvnet-common/recipe.rb
deployment/packagebuild/packages.d/vnet/openvnet-vna/recipe.rb
deployment/packagebuild/packages.d/vnet/openvnet-vnctl/recipe.rb
deployment/packagebuild/packages.d/vnet/openvnet-vnmgr/recipe.rb
deployment/packagebuild/packages.d/vnet/openvnet-webapi/recipe.rb
deployment/packagebuild/packages.d/vnet/openvnet/recipe.rb

Since FPM sets "fpm0" as the default vendor ID to package tool chain, we used to see the package file name like:
```
openvnet-common-20150519135811gite392f33.fpm0-1.x86_64.rpm
```
It is preferable to see correct vendor ID on the file name and the rpm attribute.
```
openvnet-common-20150519135811gite392f33.axsh-1.x86_64.rpm
```

Set vendor name for .rpm

---

CHANGELOG.md
vnet/lib/vnet/core/active_interface_manager.rb
vnet/lib/vnet/core/datapath_manager.rb
vnet/lib/vnet/core/interface_manager.rb
vnet/lib/vnet/core/interface_port_manager.rb
vnet/lib/vnet/core/network_manager.rb
vnet/lib/vnet/core/route_manager.rb
vnet/lib/vnet/core/router_manager.rb
vnet/lib/vnet/core/service_manager.rb
vnet/lib/vnet/core/translation_manager.rb
vnet/lib/vnet/core/tunnel_manager.rb
vnet/lib/vnet/event/notifications.rb
vnet/lib/vnet/openflow/datapath.rb
vnet/spec/vnet/event/notifications_spec.rb

#356 
Makes sure events are dropped, and queued-only, during critical stages of bootstrap such that race-conditions during initialization won't cause issues.

Feature event control

---

integration_test/lib/vnspec/spec/router_p2v_spec.rb

Test now contains all the possible routes between the different VM's to give a more detailed test result of the environment

Add all possible routes to router_p2v test

---

vnet/lib/vnet/core/port_manager.rb

Use the keys when iterating over ports during initialize_ports to avoid insert/delete hash errors due to port events.

Fix port iteration in initialize_ports

---

deployment/packagebuild/packages.d/third_party/openvnet-openvswitch/rpmbuild.sh

Building Open vSwitch 2.3.0 failed on CentOS 6.6.
Update Open vSwitch version from 2.3.0 to 2.3.1.

update ovs version from 2.3.0 to 2.3.1.

---

deployment/packagebuild/build_packages_vnet.sh

Jenkins was failing the rpmbuild because it already had done a bundle install with an rbenv managed ruby binary. I added a few lines that make sure RPM packages are built on a clean source directory. These lines happen after copying the source to the build directories so the original source directory will remain unchanged.

Fix rpmbuild dirty source dir

---

docs/content/installation.md

Some slight changes were needed to the installation guide for it to work with 0.8. Mainly redis/mysqld installation and the new commandline arguments for vnflows-monitor.

Docs update for 0.8

---

client/ruby/README.md
client/ruby/vnet_api_client.gemspec

Removed the ruby version requirement of our vnet_api_client gem. Pushed the version to 0.8.0.2 and added a version number description to the readme.

Remove client ruby version requirement

---

CHANGELOG.md
client/vnctl/lib/vnctl/cli/datapath.rb
integration_test/dataset/base.yml
integration_test/dataset/edge.yml
integration_test/dataset/edge_esxi.yml
integration_test/dataset/event.yml
integration_test/dataset/filter.yml
integration_test/dataset/lease_policy.yml
integration_test/dataset/router_p2v.yml
integration_test/dataset/router_v2v.yml
integration_test/dataset/secg.yml
integration_test/dataset/secg_reference.yml
integration_test/dataset/service.yml
integration_test/dataset/simple.yml
integration_test/lib/vnspec/spec/event_spec.rb
vnet/lib/vnet/endpoints/1.0/datapaths.rb
vnet/spec/vnet/core/filters2_spec.rb

Fixes #383.
Due to using both broadcat_mac_address and mac_address, the dp_nw API accepted nil input. For consistency with dp_rl and testing this was set to require input.
Next update will change the db to not allow nil mac_address and allow nil in the API. This will make it possible to use the default mac range group again.

Fix ci broadcast mac

---

vnet/lib/vnet/core/interface_port_manager.rb
vnet/lib/vnet/core/port_manager.rb
vnet/lib/vnet/manager.rb
vnet/lib/vnet/openflow/datapath.rb

#388
Adds proper concurrent initialization of managers with barriers that allows them to safely initialize with events being queue-only, then active as all managers have finished initializing.

Feature do_initialize

---

CHANGELOG.md
vnet/db/migrations/0008_dp_nwrl_not_null.rb
vnet/lib/vnet/endpoints/1.0/datapaths.rb
vnet/lib/vnet/endpoints/1.0/responses/datapath_network.rb
vnet/lib/vnet/endpoints/1.0/responses/datapath_route_link.rb
vnet/spec/fabricators/interface_fabricator.rb
vnet/spec/vnet/endpoints/1.0/datapaths_spec.rb

Allows passing no mac_address to dp_nw/rl and requires dp_nw/rl mac_address_id to be valid in the db.

Fix dp nwrl not null

---

CHANGELOG.md
client/vnctl/lib/vnctl/cli/network_service.rb
integration_test/dataset/base.yml
integration_test/dataset/edge.yml
integration_test/dataset/edge_esxi.yml
integration_test/dataset/event.yml
integration_test/dataset/filter.yml
integration_test/dataset/lease_policy.yml
integration_test/dataset/router_p2v.yml
integration_test/dataset/router_v2v.yml
integration_test/dataset/secg.yml
integration_test/dataset/secg_reference.yml
integration_test/dataset/service.yml
integration_test/dataset/simple.yml

Fixes network_service's 'type' to 'mode' renaming and changes the CI to use the new 'mode', while still allowing 'type' for compatibility.

Fix ci network_service mode

---

docs/content/debugging/troubleshooting.md
docs/content/installation.md

Cherry picked the single commit from https://github.com/axsh/openvnet/pull/446 so it can be published immediately, rather than waiting for the next OpenVNet release.

Change fail_mode in the published docs

---

vnet/lib/vnet/core/dp_info.rb
vnet/lib/vnet/openflow/controller.rb

Properly terminate actors before trying to join, else we always wait out the 10 second timeout when switching to a new datapath.

Fix terminate

---

vnet/lib/vnet/core/routes/base.rb

Uses different priority for flows depending on their prefix in order to ensure that e.g. 10.10.10.0/24 gets handled before 10.10.0.0/16.

Feature route priority

---

deployment/packagebuild/build_packages_vnet.sh

While optimizing the CI, I thought it would be a good idea to have this script create a `current` symlink for its yum repository. That way we can always point the integration test to that.

Rpmbuild current symlink

---

integration_test/lib/vnspec/invoker.rb
vnet/lib/vnet/core/active_port_manager.rb

* @rakshasa had added a feature to the integration test to dump logs. An unexpected side-effect was that now the integration test now always reported a success since it reacted to the log dump operation's exit status instead of the tests'.
Dumping the logs per test is a good idea but I took it out for now so the integration test reports results correctly again. We can re-implement it later but fixing the integration test first is top priority.
* While the integration test wasn't reporting failures due to the above bug, a simple nilcheck bug crept in so I fixed it.

Fix integration test

---

client/vnctl/lib/vnctl/cli/translation.rb
vnet/lib/vnet/endpoints/1.0/translations.rb
vnet/spec/vnet/endpoints/1.0/translations_spec.rb

This PR is related to #460 
The endpoint accepts `ingress_network_uuid` and `egress_network_uuid` but does nothing and returns them.

Static address with network uuid

---

vnet/Gemfile

I think it's a good idea to add comments to the gemfile when we set version requirements for certain gems. I have added these comments after merging https://github.com/axsh/openvnet/pull/450 which added Ubuntu 14.04 support.

Comments for version caps in Gemfile

---

vnet/lib/vnet/models/ip_lease.rb
vnet/lib/vnet/models/mac_lease.rb
vnet/lib/vnet/models/security_group.rb

I have been reading up on [Sequel's security considerations](http://sequel.jeremyevans.net/rdoc/files/doc/security_rdoc.html). We should *never* use string interpolation when passing arguments as strings to Sequel's Dataset#filter or Dataset#where methods, as it could open us op to SQL injection attacks.
The OpenVNet code only did this in 3 places with non user generated content so **is already 100% safe** against SQL injection but it would be better to just not have string interpolation in queries at all.

Use placeholders when passing strings to Dataset#where.

---

client/ruby/vnet_api_client.gemspec

When pushing the vnet api client gem to rubygems.org, I saw a couple of warnings in the build log and decided to fix them.
* The license wasn't formatted properly.
* The description was the same as the summary. According to [the specification](http://guides.rubygems.org/specification-reference/), description should be a longer version of the summary. Since it is not a required field, I decided to just remove it.

Update ruby client license

---

vnet/Gemfile
vnet/Gemfile.lock
vnet/lib/plugins/vdc_vnet_plugin.rb
vnet/lib/vnet/constants/openflow.rb
vnet/lib/vnet/core/datapaths/base.rb
vnet/lib/vnet/core/interface_manager.rb
vnet/lib/vnet/core/interfaces/patch.rb
vnet/lib/vnet/core/routers/base.rb
vnet/lib/vnet/core/translations/vnet_edge_handler.rb
vnet/lib/vnet/endpoints/1.0/helpers.rb
vnet/lib/vnet/openflow/arp_lookup.rb
vnet/spec/fabricators/datapath_network_fabricator.rb
vnet/spec/fabricators/datapath_route_link_fabricator.rb
vnet/spec/vnet/core/tunnel_manager_spec.rb

This patch removes the dependency to trema-edge's Trema::Mac by replacing it with Pio::Mac.

Replace Trema::Mac with Pio::Mac

---

docs/content/debugging/integration-test.md
integration_test/README.md
integration_test/bin/dev-spec

There was some documentation that still pointed at the old location of the wakame-ci-cluster scripts. Updated those.
This can skip the CI since only documentation and README files are changed.

Update CI cluster links

---

CHANGELOG.md
deployment/conf_files/etc/openvnet/vna.conf
docs/content/configuration-files/vna.md
vnet/bin/vnflows-monitor
vnet/lib/vnet/configurations/vna.rb
vnet/lib/vnet/openflow/ovs_ofctl.rb
vnet/spec/config/vna.conf
vnet/spec/vnet/configurations/vna_spec.rb

Allows VNA to take control of an Open vSwitch instance running on another host.

Remote OVS support

---

.editorconfig

[Editor Config](http://editorconfig.org/) helps to force to apply the formatting style to the source files on the supported text editors.
I acts development on Windows so that the editor has to be configured to use LF for newline code.

Apply Editor Config style

---

deployment/packagebuild/packages.d/vnet/openvnet.spec
docs/content/installation.md

Since VNA is now able to run with a remote OVS, this dependency needs to be removed.

Remove openvswitch dependency

---

deployment/packagebuild/packages.d/vnet/openvnet.spec
docs/content/installation.md

I thought we could remove the ovs dependency from vna because it is now possible to use it with a remote ovs. Unfortunately I was wrong. Even when using a remote ovs, we still require `ovs-ofctl` to be installed and unfortunately that is in the same package as ovs itself. Therefore we can't drop the dependency just yet.

Revert openvswitch dependency

---

CHANGELOG.md
client/ruby/lib/vnet_api_client/api_resources.rb
client/vnctl/lib/vnctl/cli/base.rb
client/vnctl/lib/vnctl/cli/filter.rb
integration_test/dataset/filter.yml
integration_test/lib/vnspec/spec/filter_spec.rb
vnet/lib/vnet.rb
vnet/lib/vnet/constants/filter_static.rb
vnet/lib/vnet/endpoints/1.0/filters.rb
vnet/lib/vnet/endpoints/1.0/responses/filter.rb
vnet/lib/vnet/endpoints/1.0/responses/filter_static.rb
vnet/lib/vnet/models/filter_static.rb
vnet/lib/vnet/node_api/filter.rb
vnet/spec/client/ruby/ruby_client_spec.rb
vnet/spec/vnet/endpoints/1.0/filters_spec.rb

While working on https://github.com/axsh/openvnet/pull/512 I noticed that the filters API wasn't tested either. The `PUT` route was crashing on every request and the `static` related routes were very unintuitive. Though only ingress filtering is enabled, it still required the user to give a lot of information intended for a future implementation of egress filtering.
I wrote those tests, fixed crashes and changed those static related routes.

Filter api unit tests

---

client/ruby/lib/vnet_api_client/api_resource.rb
client/ruby/lib/vnet_api_client/api_resources.rb
client/vnctl/lib/vnctl/cli/segment.rb
vnet/lib/vnet/endpoints/1.0/segments.rb
vnet/lib/vnet/node_api/segment.rb
vnet/spec/vnet/endpoints/1.0/segments_spec.rb
vnet/spec/vnet/endpoints/1.0/shared_examples/delete.rb

A while ago it was reported to me that the segments API 100% crashes on deletion. I wonder how an issue of that magnitude could ever make it through the unit tests and the answer is there were no unit tests. \*facepalm* 
So in this PR I:
* Wrote those very needed unit tests
* Fixed that guaranteed crash on deletion
* ~~Fixed another major issue where updating a segment did nothing at all~~
* Removed all segment update code from webapi and clients (which was in place before this PR). I was told updating segments should not be allowed.
* Fixed another issue where `mode` was not required in the webapi. Omitting it would set it to an empty string in the database. Wonder how VNA would have dealt with that.
Remember to test your code, people.

Fix broken segments API

---

vnet/lib/vnet/node_api/base.rb
vnet/lib/vnet/node_api/event_base.rb

Don't call transaction block by default in node_api as that is handled by the specific classes when needed.

Fix event timing

---

ci/ci.el6/rspec_rpmbuild/build.sh
ci/ci.el7/rspec_rpmbuild/build.sh

The group permissions weren't set correctly for the branch yum repositories and because of this the CI's garbage collection couldn't delete them when needed. https://ci.openvnet.org/job/garbage_collection/42/console
Fixed that.

Fix gc permission issue

---

ci/ci.el6/rspec_rpmbuild/build_packages_vnet.sh
ci/ci.el7/rspec_rpmbuild/build_packages_vnet.sh

Just a tiny fix. Creating the database through mysqladmin worked just fine but I think it is better to use rake so we notice if rake's db creation ever breaks.

Use rake to create the rspec test database

---

vnet/lib/sequel/plugins/mac_address.rb
vnet/lib/vnet/models/mac_address.rb
vnet/lib/vnet/models/network.rb
vnet/lib/vnet/models/segment.rb
vnet/lib/vnet/node_api/event_base.rb
vnet/lib/vnet/node_api/interface.rb
vnet/lib/vnet/node_api/ip_lease.rb
vnet/lib/vnet/node_api/mac_lease.rb
vnet/lib/vnet/node_api/network.rb
vnet/lib/vnet/node_api/segment.rb
vnet/spec/fabricators/mac_lease_fabricator.rb
vnet/spec/vnet/endpoints/1.0/networks_spec.rb
vnet/spec/vnet/models/network_spec.rb
vnet/spec/vnet/models/segment_spec.rb

Fixed the following bug:
* Imagine we have interface `if-aaa` in network `nw-bbb` with ip address `x.x.x.x`.
* Next we delete network `nw-bbb`.
* Now in the database the `ip_address` for x.x.x.x got destroyed but the `ip_lease` remained.
* Next time we did `vnctl show if-aaa` the webapi saw that if-aaa has an `ip_lease` and tried access the `ip_address` associated with it and display the `network` accociated with that. Since both of those have been deleted, the web api crashed with a nilclass error.
It resulted in the follow error in the log:
```
Apr 18 07:10:36 ci vnet-webapi[1047]: 172.16.3.11 - - [18/Apr/2017:07:10:36 +0000] "GET /api/interfaces/if-aaa HTTP/1.1" 200 617 0.0245
Apr 18 07:10:36 ci vnet-webapi[1047]: 2017-04-18 07:10:36 - NoMethodError - undefined method `network' for …
```

Fix network ip lease deletion

---

vnet/lib/sinatra/vnet_api_setup.rb

I was getting the following error when calling OpenVNet from terraform.
```
* openvnet_datapath.dp_sample: json: cannot unmarshal number into Go struct field OpenVNetError.code of type string  
```
The problem was that all explicitly defined error codes are returned as strings but our generic `500: internal server error` was returned numerically. I changed that one to string as well to be consistent with the rest. With this change the go client works as expected.

Fixed inconsistent error format

---

vnet/Gemfile
vnet/Gemfile.lock
vnet/lib/vnet.rb

The old version of active support seems to have a security vulnerability so I updated it and required a new file to which the `ActiveSupport::JSON` constant seems to have moved.

Update active support

---

integration_test/config/base.yml
integration_test/lib/vnspec/config.rb
integration_test/lib/vnspec/invoker.rb
integration_test/lib/vnspec/logger.rb
integration_test/lib/vnspec/spec.rb

Updated the integration test to do two passes.
VNA is started on all hosts **before** the database is populated using vnctl commands.
Execute all specs
VNA is started on all hosts **after** the database is populated using vnctl commands.
Execute all specs
Up until now the integration test only started VNA after all the vnctl commands had been executed. While implementen OpenVNet in several projects, I ran into a lot of bugs that occur only when VNA is started before. In order to reproduce those, I've added the two pass system. Now we have an environment to test against while we fix them.
For now I've set the test a configuration flag to make the integration test run the same as before, starting VNA only after vnctl commands. That way develop can remain green while we fix these problems in …

Two pass integration test
